---
title: "Medical_Drugs_Analysis_tools"
author: "Alexandre Rueda Payen"
date: "2/6/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(stringr)
library(stringi)

print(getwd())

plot_topic_model_on_condition_beta<-function(condition){
  display=read.csv2(file=paste0("./class/Medical_Drugs_Feedback/data/",str_replace_all(condition," ","_"),"/topic_model_on_condition_beta.csv"))
      # display %>%
      #   mutate(term = reorder_within(term, beta, topic)) %>%
      #   ggplot(aes(beta, term, fill = factor(topic))) +
      #   geom_col(show.legend = FALSE) +
      #   facet_wrap(~ topic, scales = "free") +
      #   scale_y_reordered()
}

sum_up_topic_model_on_condition_gamma<-function(condition) {
  data_preprocessed=read.csv2(file=paste0("./class/Medical_Drugs_Feedback/data/test_data.csv"))
  display=read.csv2(file=paste0("./class/Medical_Drugs_Feedback/data/",str_replace_all(condition," ","_"),"/topic_model_on_condition_gamma.csv"))
  display=display%>%left_join(data_preprocessed,by=c("document"="uniqueID"))
  display=(display[,c('topic','drugName','gamma','review')])
  
  for (i in 1:9) {
    print(knitr::kable(display%>%filter(topic==i), caption = paste0("Five most representative messages for topic ",i, "in condition ",condition)))
  }
}
```

# Topic models

## Birth Control

```{r, echo=F}
# condition='Birth Control'
# plot_topic_model_on_condition_beta(condition)
```

```{r, echo=FALSE}
condition='Birth Control'
sum_up_topic_model_on_condition_gamma(condition)
```

Interpretation :

## ADHD

You can also embed plots, for example:

```{r, echo=FALSE}
condition='ADHD'
plot_topic_model_on_condition_beta(condition)
```


```{r, echo=FALSE}
condition='ADHD'
sum_up_topic_model_on_condition_gamma(condition)
```

## Depression

```{r, echo=FALSE}
condition='Depression'
plot_topic_model_on_condition_beta(condition)
```
```{r, echo=FALSE}
condition='Depression'
sum_up_topic_model_on_condition_gamma(condition)
```
## Bipolar Disorde

```{r, echo=FALSE}
condition='Bipolar Disorde'
plot_topic_model_on_condition_beta(condition)
```

```{r, echo=FALSE}
condition='Bipolar Disorde'
sum_up_topic_model_on_condition_gamma(condition)
```
## Insomnia

```{r, echo=FALSE}
condition='Insomnia'
plot_topic_model_on_condition_beta(condition)
```

```{r, echo=FALSE}
condition='Insomnia'
sum_up_topic_model_on_condition_gamma(condition)
```
